site_name: Plotex


theme:
  name: "material"
  features:
    - navigation.indexes 

  font:
    text: Merriweather
    code: Roboto Mono

  logo: assets/plotex_scatter.png
  favicon: assets/plotex_scatter.png

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - mkdocstrings:
  - search
  
nav:
  - Overview: index.md
  - API: api.md
  - Frequent Snippets: frequent.md

