site_name: Plotex
theme:
  name: "material"

plugins:
  - mkdocstrings
  - search
  
nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

