site_name: Plotex
theme:
  name: "material"

plugins:
  - mkdocstrings
    handlers:
      python:
        options:
          show_submodules: true
  - search
  
nav:
  - Calculation Docs: index.md
  - How-To Guides: how-to-guides.md
  - reference.md

