site_name: Plotex
site_url: https://rg089.github.io/plotex
site_author: Rishabh Gupta
site_description: >-
  Generating elegant, publication-ready plots made simple

theme:
  name: "material"
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.share

  font:
    text: Merriweather
    code: Roboto Mono

  logo: assets/plotex_scatter.png
  favicon: assets/plotex_scatter.png

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github


plugins:
  - mkdocstrings:
  - search
  - social:
      cards_color:
        fill: "black" 
        text: "white"
      cards_font: Cinzel
  
nav:
  - Overview: index.md
  - Frequent Snippets: frequent.md
  - API: 
    - Overview of the API: api/index.md # Named as index to use it in API section directly, see `navigation.indexes`
    - Main: api/plotex_main.md
  - Changelog: changelog.md

repo_url: https://github.com/rg089/plotex
repo_name: rg089/plotex

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rg089
    - icon: fontawesome/solid/globe
      link: https://rg089.github.io
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/plotex/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rg089_    
